# Generated by Django 6.0 on 2025-12-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_chatmessage_feedback_chatmessage_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="context",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
