# Generated by Django 6.0 on 2025-12-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='feedback',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
