"""Shared constants for the GAAYATRI chatbot module."""
from __future__ import annotations

import re
from typing import Final

DEFAULT_GROQ_API_URL: Final[str] = "https://api.groq.com/openai/v1/chat/completions"
DEFAULT_GROQ_MODEL: Final[str] = "llama-3.1-8b-instant"

DECOMMISSIONED_MODEL_MAP: Final[dict[str, str]] = {
    "llama3-70b-8192": DEFAULT_GROQ_MODEL,
    "llama-3.1-70b-versatile": DEFAULT_GROQ_MODEL,
    "llama3-8b-8192": DEFAULT_GROQ_MODEL,
    "llama-3.2-8b-instant": DEFAULT_GROQ_MODEL,
    "mixtral-8x7b-32768": DEFAULT_GROQ_MODEL,
}

GREETING_PATTERN = re.compile(
    r"\b(hi|hello|hey|namaste|namaskar|vanakkam|good\s+(morning|evening|afternoon)|greetings)\b",
    re.IGNORECASE,
)

CATTLE_KEYWORDS: Final[list[str]] = [
    "cow",
    "cows",
    "gai",
    "gaayatri",
    "gaay",
    "cattle",
    "buffalo",
    "buffaloes",
    "buffalos",
    "heifer",
    "calf",
    "calves",
    "bull",
    "bullock",
    "ox",
    "oxen",
    "dairy",
    "milk",
    "milking",
    "lactation",
    "yield",
    "mastitis",
    "udder",
    "teat",
    "colostrum",
    "nutrition",
    "feed",
    "fodder",
    "ration",
    "silage",
    "hay",
    "pasture",
    "grazing",
    "supplement",
    "mineral",
    "protein",
    "energy",
    "disease",
    "illness",
    "fever",
    "infection",
    "deworm",
    "parasite",
    "tick",
    "lice",
    "vaccination",
    "vaccine",
    "pregnancy",
    "gestation",
    "heat",
    "estrus",
    "insemination",
    "fertility",
    "calving",
    "parturition",
    "dry period",
    "scours",
    "diarrhea",
    "rumen",
    "bloat",
    "hoof",
    "lameness",
    "ketosis",
    "acidosis",
    "minerals",
    "vitamins",
]

BOVINE_CORE_TERMS: Final[set[str]] = {
    "cow",
    "cows",
    "cattle",
    "buffalo",
    "buffaloes",
    "heifer",
    "calf",
    "calves",
    "bull",
    "bullock",
    "ox",
    "oxen",
    "dairy",
    "mastitis",
    "udder",
    "teat",
    "lactation",
    "milking",
    "calving",
    "gaayatri",
    "gaay",
    "herd",
    "fodder",
    "ration",
    "silage",
}

CATTLE_KEYWORD_PATTERN = re.compile(r"(" + "|".join(re.escape(k) for k in CATTLE_KEYWORDS) + r")", re.IGNORECASE)

DEFAULT_LOCATION_LABEL: Final[str] = "India (default)"
INDIA_KEYWORDS: Final[set[str]] = {"india", "bharat", "republic of india"}
IP_PATTERN = re.compile(r"\b\d{1,3}(?:\.\d{1,3}){3}\b")

HUMAN_HEALTH_TERMS: Final[set[str]] = {
    "fever",
    "ill",
    "illness",
    "sick",
    "injury",
    "fracture",
    "cough",
    "cold",
    "pain",
    "covid",
    "flu",
    "tablet",
    "pill",
    "medicine",
    "doctor",
    "hospital",
    "clinic",
    "bleeding",
    "vomit",
    "vomiting",
    "diarrhea",
    "diarrhoea",
    "headache",
    "stomach",
    "dizzy",
    "weakness",
}

HUMAN_HEALTH_CUES: Final[tuple[str, ...]] = (
    "i have",
    "i've got",
    "i am",
    "i'm",
    "i feel",
    "i need",
    "i got",
    "i suffer",
    "for me",
    "for myself",
    "my health",
    "my body",
    "my head",
    "my stomach",
    "my chest",
    "my leg",
    "my arm",
    "my back",
    "my child",
    "my baby",
    "my daughter",
    "my son",
    "my wife",
    "my husband",
    "my mother",
    "my father",
    "my parents",
    "for my child",
    "for my baby",
    "for my daughter",
    "for my son",
    "for my wife",
    "for my husband",
    "we have",
    "we are",
    "we feel",
    "our child",
    "our baby",
    "our health",
)

SELF_HARM_TERMS: Final[tuple[str, ...]] = (
    "suicide",
    "kill myself",
    "harm myself",
    "end my life",
    "self harm",
)

VIOLENCE_TERMS: Final[tuple[str, ...]] = (
    "kill someone",
    "harm someone",
    "murder",
    "make a bomb",
    "build a weapon",
    "poison someone",
)

__all__ = [
    "DEFAULT_GROQ_API_URL",
    "DEFAULT_GROQ_MODEL",
    "DECOMMISSIONED_MODEL_MAP",
    "GREETING_PATTERN",
    "CATTLE_KEYWORDS",
    "BOVINE_CORE_TERMS",
    "CATTLE_KEYWORD_PATTERN",
    "DEFAULT_LOCATION_LABEL",
    "INDIA_KEYWORDS",
    "IP_PATTERN",
    "HUMAN_HEALTH_TERMS",
    "HUMAN_HEALTH_CUES",
    "SELF_HARM_TERMS",
    "VIOLENCE_TERMS",
]
